# Generated by Django 5.2.7 on 2025-10-09 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(blank=True, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
            },
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('chat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, choices=[('mtn', 'MTN'), ('moov', 'MOOV'), ('card', 'Cart'), ('sbin', 'Celtis'), ('orange', 'Orange'), ('wave', 'wave'), ('togocom', 'Togocom'), ('airtel', 'Airtel'), ('mpesa', 'Mpsesa'), ('afrimoney', 'Afrimoney')], max_length=100, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('public_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('country_code', models.CharField(blank=True, max_length=100, null=True)),
                ('indication', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('withdrawal_message', models.CharField(blank=True, max_length=150, null=True)),
                ('deposit_api', models.CharField(choices=[('connect', 'Blaffa Connect')], default='bizao', max_length=100)),
                ('withdrawal_api', models.CharField(choices=[('connect', 'Blaffa Connect')], default='bizao', max_length=100)),
                ('payment_by_link', models.BooleanField(default=False)),
                ('otp_required', models.BooleanField(default=False)),
                ('enable', models.BooleanField(default=True)),
                ('deposit_message', models.TextField(blank=True, null=True)),
                ('active_for_deposit', models.BooleanField(default=True)),
                ('active_for_with', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_withdrawal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reward_mini_withdrawal', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('whatsapp_phone', models.CharField(blank=True, max_length=254, null=True)),
                ('minimum_solde', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('referral_bonus', models.BooleanField(default=True)),
                ('deposit_reward', models.BooleanField(default=True)),
                ('deposit_reward_percent', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('min_version', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_version', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dowload_apk_link', models.URLField(blank=True, null=True)),
                ('wave_default_link', models.URLField(blank=True, null=True)),
                ('connect_pro_password', models.CharField(blank=True, max_length=250, null=True)),
                ('connect_pro_email', models.CharField(blank=True, max_length=250, null=True)),
                ('connect_pro_token', models.TextField(blank=True, null=True)),
                ('connect_pro_refresh', models.TextField(blank=True, null=True)),
                ('expired_connect_pro_token', models.DateTimeField(blank=True, null=True)),
                ('orange_default_link', models.URLField(blank=True, null=True)),
                ('mtn_default_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('file', models.FileField(blank=True, null=True, upload_to='media')),
            ],
            options={
                'verbose_name': 'championnat',
                'verbose_name_plural': 'championnats',
            },
        ),
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('bet_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.appname')),
            ],
            options={
                'verbose_name': 'Solde',
                'verbose_name_plural': 'Soldes',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bet_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.appname')),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
            },
        ),
        migrations.CreateModel(
            name='IDLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_app_id', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('app_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.appname')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ID Link',
                'verbose_name_plural': 'ID Links',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recompense',
                'verbose_name_plural': 'Recompenses',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('type_trans', models.CharField(choices=[('deposit', 'Dépôt'), ('withdrawal', 'Retrait'), ('disbursements', 'Disbursements')], max_length=120)),
                ('status', models.CharField(choices=[('init_payment', 'En entente'), ('accept', 'Accept'), ('error', 'Erreur'), ('pending', 'Pendind')], default='pending', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('wehook_receive_at', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('user_app_id', models.CharField(blank=True, max_length=120, null=True)),
                ('withdriwal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('transaction_link', models.TextField(blank=True, null=True)),
                ('net_payable_amout', models.PositiveIntegerField(blank=True, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=20, null=True)),
                ('public_id', models.CharField(blank=True, max_length=250, null=True)),
                ('already_process', models.BooleanField(default=False)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.appname')),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobcash_inte.network')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reason_bonus', models.CharField(max_length=255)),
                ('bonus_with', models.BooleanField(default=False)),
                ('bonus_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobcash_inte.transaction')),
            ],
            options={
                'verbose_name': 'Bonus',
                'verbose_name_plural': 'Bonuss',
            },
        ),
        migrations.CreateModel(
            name='UserLimite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
