# Generated by Django 5.2.7 on 2025-10-15 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_telegramuser'),
        ('mobcash_inte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deposit_reward_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fail_webhook_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='old_public_id',
            field=models.CharField(choices=[('init_payment', 'En entente'), ('accept', 'Accept'), ('error', 'Erreur'), ('pending', 'Pendind')], default='pending', max_length=120),
        ),
        migrations.AddField(
            model_name='transaction',
            name='old_status',
            field=models.CharField(choices=[('init_payment', 'En entente'), ('accept', 'Accept'), ('error', 'Erreur'), ('pending', 'Pendind')], default='pending', max_length=120),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pending_webhook_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('web', 'Web'), ('bot', 'bot')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='success_webhook_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='telegram_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.telegramuser'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='timeout_webhook_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_trans',
            field=models.CharField(choices=[('deposit', 'Dépôt'), ('withdrawal', 'Retrait'), ('disbursements', 'Disbursements'), ('reward', 'reward')], max_length=120),
        ),
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=120, unique=True)),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobcash_inte.network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
