# Generated by Django 5.2 on 2025-10-15 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_telegramuser'),
        ('mobcash_inte', '0002_transaction_deposit_reward_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphone',
            name='telegram_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.telegramuser'),
        ),
    ]
