# Generated by Django 5.2 on 2025-10-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobcash_inte', '0005_idlink_telegram_user_alter_idlink_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idlink',
            name='user_app_id',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
