# Generated by Django 5.2.7 on 2025-10-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobcash_inte', '0006_alter_idlink_user_app_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='enable',
        ),
        migrations.AddField(
            model_name='transaction',
            name='webhook_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='deposit_api',
            field=models.CharField(choices=[('connect', 'Blaffa Connect')], default='connect', max_length=100),
        ),
        migrations.AlterField(
            model_name='network',
            name='withdrawal_api',
            field=models.CharField(choices=[('connect', 'Blaffa Connect')], default='connect', max_length=100),
        ),
    ]
