# Generated by Django 5.2.7 on 2025-10-16 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobcash_inte', '0007_remove_network_enable_transaction_webhook_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobcash_inte.transaction'),
        ),
    ]
