# Generated by Django 5.2.7 on 2025-10-09 15:55

import django.contrib.auth.models
import django.contrib.auth.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('hash', models.CharField(blank=True, max_length=120, null=True)),
                ('cashdeskid', models.CharField(blank=True, max_length=120, null=True)),
                ('cashierpass', models.CharField(blank=True, max_length=120, null=True)),
                ('deposit_tuto_link', models.URLField(blank=True, null=True)),
                ('withdrawal_tuto_link', models.URLField(blank=True, null=True)),
                ('why_withdrawal_fail', models.URLField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('street', models.CharField(blank=True, max_length=124, null=True)),
                ('minimun_deposit', models.PositiveIntegerField(blank=True, null=True)),
                ('max_deposit', models.PositiveIntegerField(blank=True, null=True)),
                ('minimun_with', models.PositiveIntegerField(blank=True, null=True)),
                ('max_win', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'App name',
                'verbose_name_plural': 'App names',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=256, unique=True)),
                ('otp', models.CharField(max_length=100, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_block', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('referrer_code', models.CharField(blank=True, max_length=1000, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_supperuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
